// DEBUG-only: inspect a single loan's oferta. GET ?loanId=NNN&fields=1 returns the computed {{token}}
// map as JSON (no chromium) for value QA. The rendered PDF preview is produced by the background
// worker now (the lean web image ships no chromium), so the chromium branch returns 501 instead of
// launching a browser. Behind the normal auth middleware; not linked from any UI.
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { ofertaFields } from '@/lib/oferta-pdf';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
  const loanId = Number(req.nextUrl.searchParams.get('loanId'));
  const ins = Number(req.nextUrl.searchParams.get('ins')) || 0;
  if (!Number.isFinite(loanId) || loanId <= 0) return NextResponse.json({ error: 'loanId required' }, { status: 400 });
  const loan = await prisma.loan.findUnique({ where: { id: loanId } });
  if (!loan) return NextResponse.json({ error: 'loan not found' }, { status: 404 });
  const firm = loan.branchCode ? await prisma.firm.findUnique({ where: { code: loan.branchCode } }) : null;

  // ?fields=1 → return the computed {{token}} map as JSON (no chromium) for value QA.
  if (req.nextUrl.searchParams.get('fields') === '1') {
    return NextResponse.json(ofertaFields(loan as never, firm ?? {}, loan.clientName, loan.pinfl, ins));
  }

  // The lean web image has no chromium — the actual PDF is rendered by the worker.
  return NextResponse.json({ error: 'PDF preview is generated by the worker; use the per-case download.' }, { status: 501 });
}
